import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import test from './assets/fonts/'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

const brandonGrotFont = localFont({
  src: [
    {
      path: './assets/fonts//Brandon_reg.otf',
      weight: '400',
    },
    {
      path: './assets/fonts/Brandon_bld.otf',
      weight: '700',
    },
    {
      path: './assets/fonts/Brandon_blk.otf',
      weight: '900',
    },
  ],
  variable: '--font-brandon',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${brandonGrotFont.variable} antialiased font-brandon text-base`}
      >
        {children}
      </body>
    </html>
  )
}
